In [1]:
import os
from pathlib import Path

import geopandas as gpd
import pandas as pd

from shadowroutes.config import settings

src_path = Path('../')
os.chdir(src_path)

## Parameters

In [2]:
# Index panels - obtained in November 2025
path_protection_panel = Path(settings.DATA_ROOT / 'processed' / 'protection_index_panel.csv')
path_collusion_panel = Path(settings.DATA_ROOT / 'processed' / 'collusion_index_panel.csv')
path_mining_panel = Path(settings.DATA_ROOT / 'processed' / 'mining_index_panel.csv')

# Population estimates (mid-year) from CONAPO - obtained in October 2025
data_path_pop_m = Path(settings.DATA_ROOT / 'conapo' / 'raw' / 'pobproy_quinq1.csv')

# Municipalities geodata from INEGI - obtained in November 2025
path_muni_geo = Path(settings.DATA_ROOT / 'marco_geoestadistico_inegi' / 'raw' / 'mg_2024_integrado' / '00mun.shp')

# Output path
out_muni_panel = Path(settings.DATA_ROOT / 'processed' / 'environment_panel.csv')
out_adjacency_df = Path(settings.DATA_ROOT / 'processed' / 'adjacency_nodes.csv')

## Data

In [3]:
# Loads data
gdf_munis = gpd.read_file(path_muni_geo)
gdf_munis = gdf_munis.to_crs("EPSG:4326")

print(gdf_munis.shape)
gdf_munis.head(10)

(2478, 5)

,CVEGEO,CVE_ENT,CVE_MUN,NOMGEO,geometry
0,01005,01,005,Jesús María,"POLYGON ((-102.35391 22.06255, -102.35312 22.0..."
1,01008,01,008,San José de Gracia,"POLYGON ((-102.45537 22.31212, -102.45501 22.3..."
2,01001,01,001,Aguascalientes,"POLYGON ((-102.10732 22.07476, -102.10699 22.0..."
3,01004,01,004,Cosío,"POLYGON ((-102.29739 22.45527, -102.29554 22.4..."
4,01011,01,011,San Francisco de los Romo,"POLYGON ((-102.15938 22.099, -102.15638 22.097..."
5,01006,01,006,Pabellón de Arteaga,"POLYGON ((-102.25345 22.18302, -102.2513 22.18..."
6,01003,01,003,Calvillo,"POLYGON ((-102.68534 22.10558, -102.6847 22.10..."
7,01010,01,010,El Llano,"POLYGON ((-102.03427 22.06936, -102.03222 22.0..."
8,01002,01,002,Asientos,"POLYGON ((-102.0629 22.30175, -102.06257 22.30..."
9,01009,01,009,Tepezalá,"POLYGON ((-102.17738 22.36243, -102.17968 22.3..."

In [4]:
# Loads data
df_pop_m = pd.read_csv(data_path_pop_m, encoding='utf-8')
print(f'File read: {print(data_path_pop_m.name)}')

print(df_pop_m.shape)
df_pop_m.head()

pobproy_quinq1.csv
File read: None
(252450, 27)

,CLAVE,CLAVE_ENT,NOM_ENT,NOM_MUN,SEXO,ANO,POB_TOTAL,POB_00_04,POB_05_09,POB_010_014,...,POB_50_54,POB_55_59,POB_60_64,POB_65_69,POB_70_74,POB_75_79,POB_80_84,POB_85_mm,fecha,etiqueta_estado
0,1001,1,Aguascalientes,Aguascalientes,HOMBRES,1990,243891,35865,32966,30713,...,6323,5051,4206,3265,2316,1617,1022,681,1990-01-01,Aguascalientes
1,1001,1,Aguascalientes,Aguascalientes,MUJERES,1990,255948,34812,31927,30190,...,7188,6081,5161,4112,3041,2215,1474,1063,1990-01-01,Aguascalientes
2,1001,1,Aguascalientes,Aguascalientes,HOMBRES,1991,252446,36879,33745,31208,...,6705,5261,4336,3360,2397,1654,1034,715,1991-01-01,Aguascalientes
3,1001,1,Aguascalientes,Aguascalientes,MUJERES,1991,264829,35825,32697,30583,...,7569,6289,5329,4255,3165,2267,1495,1121,1991-01-01,Aguascalientes
4,1001,1,Aguascalientes,Aguascalientes,HOMBRES,1992,261132,37908,34523,31773,...,7108,5486,4461,3451,2491,1694,1042,748,1992-01-01,Aguascalientes

In [5]:
# Loads data
df_prot = pd.read_csv(path_protection_panel, encoding='utf-8')
print(f'File read: {print(path_protection_panel.name)}')

print(df_prot.shape)
df_prot.head()

protection_index_panel.csv
File read: None
(323, 9)

,muni_id,municipality,year,state_id,state,pol_mun_rate_100k,federal_presence,prot_raw,prot_idx
0,12001,Acapulco de Juárez,2025,12,Guerrero,0.4,1,50.380722,0.104702
1,12002,Ahuacuotzingo,2025,12,Guerrero,123.9,0,123.851378,0.257391
2,12003,Ajuchitlán del Progreso,2025,12,Guerrero,18.7,0,18.657214,0.038774
3,12004,Alcozauca de Guerrero,2025,12,Guerrero,198.1,0,198.064371,0.411622
4,12005,Alpoyeca,2025,12,Guerrero,207.5,0,207.468880,0.431166

In [6]:
# Loads data
df_coll = pd.read_csv(path_collusion_panel, encoding='utf-8')
print(f'File read: {print(path_collusion_panel.name)}')

print(df_coll.shape)
df_coll.head()

collusion_index_panel.csv
File read: None
(163, 11)

,state_id,state,muni_id,municipality,insecurity_mun,mistrust_police,corr_police,ineff_police,collusion_idx_raw,collusion_idx,year
0,12,GUERRERO,12001,ACAPULCO DE JUAREZ,0.891895,0.614207,0.773391,0.604499,0.723517,0.783212,2025
1,12,GUERRERO,12003,AJUCHITLAN DEL PROGRESO,0.558824,0.333333,0.769231,0.566667,0.577662,0.572155,2025
2,12,GUERRERO,12006,APAXTLA,0.272689,0.298229,0.708343,0.429791,0.462973,0.406196,2025
3,12,GUERRERO,12007,ARCELIA,0.332788,0.380682,0.426025,0.382584,0.387353,0.296772,2025
4,12,GUERRERO,12010,ATLIXTAC,0.500039,0.484122,0.342120,0.460336,0.432848,0.362603,2025

In [7]:
# Loads data
df_mining = pd.read_csv(path_mining_panel, encoding='utf-8')
print(f'File read: {print(path_mining_panel.name)}')

print(df_mining.shape)
df_mining.head()

mining_index_panel.csv
File read: None
(323, 8)

,state_id,muni_id,municipality,num_concessions,has_mining,concessions_log,concessions_scaled,mining_idx
0,12,12001,Acapulco de Juárez,6,1,1.945910,0.431383,0.715692
1,12,12002,Ahuacuotzingo,0,0,0.000000,0.000000,0.000000
2,12,12003,Ajuchitlán del Progreso,4,1,1.609438,0.356792,0.678396
3,12,12004,Alcozauca de Guerrero,0,0,0.000000,0.000000,0.000000
4,12,12005,Alpoyeca,0,0,0.000000,0.000000,0.000000

### Preprocessing

#### gdf munis

In [8]:
gdf_munis.drop('CVE_MUN', axis=1, inplace=True)
print(gdf_munis.columns)

Index(['CVEGEO', 'CVE_ENT', 'NOMGEO', 'geometry'], dtype='object')

In [9]:
gdf_munis.rename(columns={'CVEGEO': 'muni_id', 'CVE_ENT': 'state_id', 'NOMGEO': 'municipality'}, inplace=True)
gdf_munis = gdf_munis[gdf_munis.state_id.isin(["12", "16", "15"])].reset_index(drop=True)

gdf_munis['muni_id'] = gdf_munis['muni_id'].astype('str')
gdf_munis['state_id'] = gdf_munis['state_id'].astype('int64')
gdf_munis['municipality'] = gdf_munis['municipality'].astype('str')


print(gdf_munis.shape)
gdf_munis.head()

(323, 4)

,muni_id,state_id,municipality,geometry
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969..."
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5..."
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016..."
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ..."
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5..."

#### Population by municipality

In [10]:
df_pop_m.columns = df_pop_m.columns.str.lower()
df_pop_m.rename(columns={'ano': 'year', 'clave_ent': 'state_id', 'nom_ent': 'state', 'clave': 'muni_id', 'nom_mun': 'municipality', 'sexo': 'sex', 'pob_total': 'pop_total'}, 
                  inplace=True)

df_pop_m = df_pop_m[df_pop_m.state_id.isin([12, 16, 15])]
df_pop_m = df_pop_m[df_pop_m.year == 2025].reset_index(drop=True)

print(df_pop_m.shape)
df_pop_m.head()

(646, 27)

,muni_id,state_id,state,municipality,sex,year,pop_total,pob_00_04,pob_05_09,pob_010_014,...,pob_50_54,pob_55_59,pob_60_64,pob_65_69,pob_70_74,pob_75_79,pob_80_84,pob_85_mm,fecha,etiqueta_estado
0,12001,12,Guerrero,Acapulco de Juárez,HOMBRES,2025,374985,29004,31618,31862,...,21433,19706,17420,13456,9239,5893,3365,2817,2025-01-01,Guerrero
1,12001,12,Guerrero,Acapulco de Juárez,MUJERES,2025,412991,27706,30097,30352,...,26676,23821,20436,16073,11165,7496,4629,3984,2025-01-01,Guerrero
2,12002,12,Guerrero,Ahuacuotzingo,HOMBRES,2025,11745,1511,1480,1410,...,461,400,351,285,228,196,137,134,2025-01-01,Guerrero
3,12002,12,Guerrero,Ahuacuotzingo,MUJERES,2025,13285,1431,1461,1421,...,533,477,406,333,273,243,180,162,2025-01-01,Guerrero
4,12003,12,Guerrero,Ajuchitlán del Progreso,HOMBRES,2025,18054,1918,1914,1743,...,723,671,648,576,455,349,279,246,2025-01-01,Guerrero

In [11]:
df_pop = df_pop_m.groupby(['year', 'muni_id', 'state'], as_index=False)['pop_total'].sum()

df_pop['muni_id'] = df_pop['muni_id'].astype('str')
df_pop['state'] = df_pop['state'].astype('str')
df_pop['year'] = df_pop['year'].astype('int64')
df_pop['pop_total'] = df_pop['pop_total'].astype('int64')

print(df_pop.shape)
df_pop.head()

(323, 4)

   year muni_id     state  pop_total
0  2025   12001  Guerrero     787976
1  2025   12002  Guerrero      25030
2  2025   12003  Guerrero      37519
3  2025   12004  Guerrero      22215
4  2025   12005  Guerrero       8194

In [12]:
# Get mean and median of population across all municipalities

print(f'Mean across all municipalities: {df_pop.pop_total.mean()}')
print(f'Median across all municipalities: {df_pop.pop_total.median()}')

Mean across all municipalities: 81658.31888544891
Median across all municipalities: 27736.0

#### Protection panel

In [13]:
df_prot = df_prot.loc[:, ['muni_id', 'prot_idx']]

df_prot['muni_id'] = df_prot['muni_id'].astype('str')
df_prot['prot_idx'] = df_prot['prot_idx'].astype(float)

print(df_prot.shape)
df_prot.head()

(323, 2)

  muni_id  prot_idx
0   12001  0.104702
1   12002  0.257391
2   12003  0.038774
3   12004  0.411622
4   12005  0.431166

In [14]:
# Rescale protection index
df_prot["prot_idx"] = df_prot["prot_idx"] / df_prot["prot_idx"].max()

#### Mining panel

In [15]:
df_mining = df_mining.loc[:, ['muni_id', 'mining_idx']]

df_mining['muni_id'] = df_mining['muni_id'].astype('str')
df_mining['mining_idx'] = df_mining['mining_idx'].astype(float)

print(df_mining.shape)
df_mining.head()

(323, 2)

  muni_id  mining_idx
0   12001    0.715692
1   12002    0.000000
2   12003    0.678396
3   12004    0.000000
4   12005    0.000000

#### Collusion panel

In [16]:
df_coll = df_coll.loc[:, ['muni_id', 'collusion_idx']]

df_coll['muni_id'] = df_coll['muni_id'].astype('str')
df_coll['collusion_idx'] = df_coll['collusion_idx'].astype(float)

print(df_coll.shape)
df_coll.head()

(163, 2)

  muni_id  collusion_idx
0   12001       0.783212
1   12003       0.572155
2   12006       0.406196
3   12007       0.296772
4   12010       0.362603

In [17]:
df_coll_fill = gdf_munis.merge(df_coll.loc[:, ['muni_id', 'collusion_idx']], on=['muni_id'], how='left')

print(df_coll_fill.shape)
df_coll_fill.head()

(323, 5)

,muni_id,state_id,municipality,geometry,collusion_idx
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969...",NaN
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5...",NaN
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016...",NaN
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ...",NaN
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5...",NaN

In [18]:
df_coll_fill.isna().sum()

muni_id            0
state_id           0
municipality       0
geometry           0
collusion_idx    160
dtype: int64

In [19]:
# The state mean is used to fill the nan gaps
coll_idx_mean = df_coll_fill['collusion_idx'].mean()
df_coll_fill['collusion_idx'].fillna(coll_idx_mean, inplace=True)

df_coll_fill = df_coll_fill.loc[:, ['muni_id', 'collusion_idx']]

print(df_coll_fill.shape)
df_coll_fill.head()

(323, 2)

C:\Users\penny\AppData\Local\Temp\ipykernel_17848\4091078358.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_coll_fill['collusion_idx'].fillna(coll_idx_mean, inplace=True)

  muni_id  collusion_idx
0   12033       0.592026
1   12031       0.592026
2   12083       0.592026
3   12082       0.592026
4   12073       0.592026

In [20]:
df_coll_fill.isna().sum()

muni_id          0
collusion_idx    0
dtype: int64

### Merge

In [21]:
# 1) Start from municipalities and merge with population
df_munis = gdf_munis.merge(df_pop, on=["muni_id"], how="left")

print(df_munis.shape)
df_munis.head()

(323, 7)

,muni_id,state_id,municipality,geometry,year,state,pop_total
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969...",2025,Guerrero,18207
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5...",2025,Guerrero,6913
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016...",2025,Guerrero,11563
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ...",2025,Guerrero,10136
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5...",2025,Guerrero,18026

In [22]:
# 2) Merge protection index
df_munis = df_munis.merge(df_prot, on=["muni_id"], how="left")

print(df_munis.shape)
df_munis.head()

(323, 8)

,muni_id,state_id,municipality,geometry,year,state,pop_total,prot_idx
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969...",2025,Guerrero,18207,0.342432
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5...",2025,Guerrero,6913,0.103911
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016...",2025,Guerrero,11563,0.000000
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ...",2025,Guerrero,10136,0.000000
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5...",2025,Guerrero,18026,0.138348

In [23]:
# 3) Merge mining index
df_munis = df_munis.merge(df_mining, on=["muni_id"], how="left")

print(df_munis.shape)
df_munis.head()

(323, 9)

,muni_id,state_id,municipality,geometry,year,state,pop_total,prot_idx,mining_idx
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969...",2025,Guerrero,18207,0.342432,0.000000
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5...",2025,Guerrero,6913,0.103911,0.698605
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016...",2025,Guerrero,11563,0.000000,0.000000
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ...",2025,Guerrero,10136,0.000000,0.000000
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5...",2025,Guerrero,18026,0.138348,0.826372

In [24]:
# 4) Merge collusion index (ENVIPE)
df_munis = df_munis.merge(df_coll_fill, on=["muni_id"], how="left")

print(df_munis.shape)
df_munis.head()

(323, 10)

,muni_id,state_id,municipality,geometry,year,state,pop_total,prot_idx,mining_idx,collusion_idx
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969...",2025,Guerrero,18207,0.342432,0.000000,0.592026
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5...",2025,Guerrero,6913,0.103911,0.698605,0.592026
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016...",2025,Guerrero,11563,0.000000,0.000000,0.592026
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ...",2025,Guerrero,10136,0.000000,0.000000,0.592026
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5...",2025,Guerrero,18026,0.138348,0.826372,0.592026

In [25]:
# Checks the merged data
print(df_munis.isna().mean(), '\n')
print(df_munis[["mining_idx", "prot_idx", "collusion_idx"]].describe())

muni_id          0.0
state_id         0.0
municipality     0.0
geometry         0.0
year             0.0
state            0.0
pop_total        0.0
prot_idx         0.0
mining_idx       0.0
collusion_idx    0.0
dtype: float64

       mining_idx    prot_idx  collusion_idx
count  323.000000  323.000000     323.000000
mean     0.306608    0.282614       0.592026
std      0.364584    0.169938       0.124335
min      0.000000    0.000000       0.000000
25%      0.000000    0.171666       0.588238
50%      0.000000    0.276526       0.592026
75%      0.678396    0.378169       0.601098
max      1.000000    1.000000       1.000000

In [26]:
df_munis["node_id"] = df_munis["muni_id"] 
df_munis.head()

,muni_id,state_id,municipality,geometry,year,state,pop_total,prot_idx,mining_idx,collusion_idx,node_id
0,12033,12,Huamuxtitlán,"POLYGON ((-98.47244 17.97081, -98.47298 17.969...",2025,Guerrero,18207,0.342432,0.000000,0.592026,12033
1,12031,12,General Canuto A. Neri,"POLYGON ((-100.07588 18.54483, -100.07398 18.5...",2025,Guerrero,6913,0.103911,0.698605,0.592026,12031
2,12083,12,Ñuu Savi,"POLYGON ((-98.97829 17.01672, -98.97823 17.016...",2025,Guerrero,11563,0.000000,0.000000,0.592026,12083
3,12082,12,Las Vigas,"POLYGON ((-99.23351 16.824, -99.233 16.82325, ...",2025,Guerrero,10136,0.000000,0.000000,0.592026,12082
4,12073,12,Zirándaro,"POLYGON ((-101.28169 18.54467, -101.28126 18.5...",2025,Guerrero,18026,0.138348,0.826372,0.592026,12073

In [27]:
df_munis.dtypes

muni_id            object
state_id            int64
municipality       object
geometry         geometry
year                int64
state              object
pop_total           int64
prot_idx          float64
mining_idx        float64
collusion_idx     float64
node_id            object
dtype: object

In [28]:
data_pop_m = pd.read_csv(data_path_pop_m, encoding='utf-8')
print(f'File read: {print(data_path_pop_m.name)}')

print(data_pop_m.shape)
data_pop_m.head()

pobproy_quinq1.csv
File read: None
(252450, 27)

,CLAVE,CLAVE_ENT,NOM_ENT,NOM_MUN,SEXO,ANO,POB_TOTAL,POB_00_04,POB_05_09,POB_010_014,...,POB_50_54,POB_55_59,POB_60_64,POB_65_69,POB_70_74,POB_75_79,POB_80_84,POB_85_mm,fecha,etiqueta_estado
0,1001,1,Aguascalientes,Aguascalientes,HOMBRES,1990,243891,35865,32966,30713,...,6323,5051,4206,3265,2316,1617,1022,681,1990-01-01,Aguascalientes
1,1001,1,Aguascalientes,Aguascalientes,MUJERES,1990,255948,34812,31927,30190,...,7188,6081,5161,4112,3041,2215,1474,1063,1990-01-01,Aguascalientes
2,1001,1,Aguascalientes,Aguascalientes,HOMBRES,1991,252446,36879,33745,31208,...,6705,5261,4336,3360,2397,1654,1034,715,1991-01-01,Aguascalientes
3,1001,1,Aguascalientes,Aguascalientes,MUJERES,1991,264829,35825,32697,30583,...,7569,6289,5329,4255,3165,2267,1495,1121,1991-01-01,Aguascalientes
4,1001,1,Aguascalientes,Aguascalientes,HOMBRES,1992,261132,37908,34523,31773,...,7108,5486,4461,3451,2491,1694,1042,748,1992-01-01,Aguascalientes

In [29]:
data_pop_m.columns = data_pop_m.columns.str.lower()
data_pop_m.rename(columns={'ano': 'year', 'clave_ent': 'state_id', 'nom_ent': 'state', 'clave': 'muni_id', 'nom_mun': 'municipality', 'sexo': 'sex', 'pob_total': 'pop_total'}, 
                  inplace=True)
data_pop_m['state_id'] = data_pop_m['state_id'].astype('int64')
data_pop_m.columns

Index(['muni_id', 'state_id', 'state', 'municipality', 'sex', 'year',
       'pop_total', 'pob_00_04', 'pob_05_09', 'pob_010_014', 'pob_015_019',
       'pob_20_24', 'pob_25_29', 'pob_30_34', 'pob_35_39', 'pob_40_44',
       'pob_45_49', 'pob_50_54', 'pob_55_59', 'pob_60_64', 'pob_65_69',
       'pob_70_74', 'pob_75_79', 'pob_80_84', 'pob_85_mm', 'fecha',
       'etiqueta_estado'],
      dtype='object')

In [30]:
# Filter data set to 2025 only
pop_filtered_m = data_pop_m[data_pop_m.year == 2025].reset_index(drop=True)

# Filter data set to 2025 only
pop_filtered_m = pop_filtered_m[pop_filtered_m.state_id.isin([12, 16, 15])].reset_index(drop=True)
print(pop_filtered_m.state.unique())

print(pop_filtered_m.shape)
pop_filtered_m.head()

['Guerrero' 'México' 'Michoacán de Ocampo']
(646, 27)

,muni_id,state_id,state,municipality,sex,year,pop_total,pob_00_04,pob_05_09,pob_010_014,...,pob_50_54,pob_55_59,pob_60_64,pob_65_69,pob_70_74,pob_75_79,pob_80_84,pob_85_mm,fecha,etiqueta_estado
0,12001,12,Guerrero,Acapulco de Juárez,HOMBRES,2025,374985,29004,31618,31862,...,21433,19706,17420,13456,9239,5893,3365,2817,2025-01-01,Guerrero
1,12001,12,Guerrero,Acapulco de Juárez,MUJERES,2025,412991,27706,30097,30352,...,26676,23821,20436,16073,11165,7496,4629,3984,2025-01-01,Guerrero
2,12002,12,Guerrero,Ahuacuotzingo,HOMBRES,2025,11745,1511,1480,1410,...,461,400,351,285,228,196,137,134,2025-01-01,Guerrero
3,12002,12,Guerrero,Ahuacuotzingo,MUJERES,2025,13285,1431,1461,1421,...,533,477,406,333,273,243,180,162,2025-01-01,Guerrero
4,12003,12,Guerrero,Ajuchitlán del Progreso,HOMBRES,2025,18054,1918,1914,1743,...,723,671,648,576,455,349,279,246,2025-01-01,Guerrero

In [31]:
df_pop_yearly_m = pop_filtered_m.groupby(['municipality', 'year', 'muni_id', 'state_id', 'state'], as_index=False)['pop_total'].sum()
df_pop_yearly_m

,municipality,year,muni_id,state_id,state,pop_total
0,Acambay de Ruíz Castañeda,2025,15001,15,México,70196
1,Acapulco de Juárez,2025,12001,12,Guerrero,787976
2,Acatepec,2025,12076,12,Guerrero,43859
3,Acolman,2025,15002,15,México,189927
4,Acuitzio,2025,16001,16,Michoacán de Ocampo,11525
...,...,...,...,...,...,...
318,Zitácuaro,2025,16112,16,Michoacán de Ocampo,154483
319,Zumpahuacán,2025,15119,15,México,19879
320,Zumpango,2025,15120,15,México,319152
321,Álvaro Obregón,2025,16003,16,Michoacán de Ocampo,25302
322,Ñuu Savi,2025,12083,12,Guerrero,11563

### Save data

In [32]:
df_munis.to_csv(out_muni_panel, index=False)

## Create adjacency dataframe

In [30]:
# Create adjacency


sindex = gdf_munis.sindex
edges = []

for idx, row in gdf_munis.iterrows():
    geom = row.geometry
    muni_i = row["muni_id"]

    # candidates from bounding box
    candidates = list(sindex.intersection(geom.bounds))

    for cand in candidates:
        if cand <= idx:
            continue
        
        geom_j = gdf_munis.loc[cand, "geometry"]
        muni_j = gdf_munis.loc[cand, "muni_id"]

        # check if polygons actually touch
        if geom.touches(geom_j) or geom.intersects(geom_j):
            edges.append((muni_i, muni_j))

edges_df = pd.DataFrame(edges, columns=["source", "target"])

In [31]:
print(edges_df.shape)
edges_df.head()

(859, 2)

  source target
0  12033  12066
1  12033  12005
2  12033  12024
3  12033  12045
4  12033  12070

In [32]:
# Map the node id to the edges data frame

id_map = dict(zip(df_munis["muni_id"], df_munis["node_id"], strict=False))

edges_df["source"] = edges_df["source"].map(id_map)
edges_df["target"] = edges_df["target"].map(id_map)

In [37]:
edges_df = edges_df.dropna(subset=["source", "target"])
print(edges_df.shape)

(859, 2)

### Save data

In [35]:
edges_df.to_csv(out_adjacency_df, index=False)